### ISSUE TITLE
First Day Call Resolution Options

### ISSUE THREAD

**Issue by timeracers** [EnigmaDragons/MegaBuy#14]
The worker's job is to answer calls and either refer them to info or troubleshooting.

**Comment by SilasReinagel** [comment]
What does "Troubleshooting mean"? Does this ticket just mean I can present two buttons with any those words on them?

**Comment by timeracers** [comment]
You get two options one of them is refer them to info which ends the call but when incorrect costs 2 megabits. The other is refer them to troubleshooting which ends the call but when incorrect costs 2 megabits.
