### ISSUE TITLE
Call Ratings

### ISSUE THREAD

**Issue by timeracers** [EnigmaDragons/MegaBuy#16]
When you get a call you the caller starts with 15 patience over time. At 15 patience they give 5 stars. 14 - 13 = 4 stars. 12- 10 = 3 stars. 9 - 6 = 2 stars. 5 -1 = 1 star. > 0 = hangs up.

**Comment by SilasReinagel** [comment]
3 * X is not a clear business requirement. Please clarify.

**Comment by SilasReinagel** [comment]
Separate this out into tickets per use case. Each ticket should be very small. Just a singular rule.

**Comment by timeracers** [comment]
Example caller:
Says: "My package has not arrived yet and it has been over 3 days. They said they would do it in 3 days."
Correct: Refer to troubleshooting.
Time Unit: 5 seconds.

So if you end in 18 seconds you would have spent 4 time units (rounded up) which would cost a total of 1 patience.
