### ISSUE TITLE
Social Mistakes vs Technical Mistakes

### ISSUE THREAD

**Issue by timeracers** [EnigmaDragons/MegaBuy#18]
Some mistakes will reduce the caller's patience but other mistakes like giving them a refund when you aren't suppose to will negate the call's pay and dock your pay.

**Comment by SilasReinagel** [comment]
Needs more concrete details/numbers.

**Comment by SilasReinagel** [comment]
Need to know how to differentiate between types of mistakes. What mistake types are there?

**Comment by timeracers** [comment]
Each option will do something and if incorrect will also either reduce the caller's patience as specified or dock pay as specified.
